create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  price integer not null,
  old_price integer,
  color text,
  image text not null,
  badge text,
  tone text,
  created_at timestamptz default now()
);

alter table products enable row level security;
create policy "Products are public" on products for select using (true);
